name: Demo CI

on:
  push:
    paths:
      - '!README.md'
      - '!LICENSE'
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["build"]
    types: [requested]
    branches:
      - 'main'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Use Node.js 18
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: '.nvmrc'
      - run: npm ci
      - run: npm test
      - run: docker build . -t greenict/demo-api
      - run: npm run lint
